acrossHibernate:
  persistence-context-in-view:
    handler: filter

debugWebModule:
  security:
    password: test
    ip-addresses:

logging:
  request-response:
    enabled: true
    paused: false
  method:
    enabled: true
    default-minimum-duration: 5

springMobile:
  device-resolver-registration: interceptor

userModule:
  enable-default-acls: true
